### ISSUE TITLE
'make bax2bam' fails with "Package 'htslib' not found"

### ISSUE THREAD

**Issue by romankap** [PacificBiosciences/bax2bam#2]
Hello,
When I use 'make bax2bam' with pitchfork (preceded by 'make init' and 'make blasr' according to the instructions), I get the following error:

> -- Checking for module 'htslib'
> -- Package 'htslib' not found
> CMake Error at /home/roman/ccs/pitchfork/deployment/share/cmake-3.4/Modules/FindPkgConfig.cmake:360 (message):
> A required package was not found
> Call Stack (most recent call first):
> /home/roman/ccs/pitchfork/deployment/share/cmake-3.4/Modules/FindPkgConfig.cmake:522 (_pkg_check_modules_internal)
> CMakeLists.txt:69 (pkg_check_modules)

Before the error, 'htslib', 'samtools' and 'blasr' were successfully compiled.

The 'htslib' distribution used by 'pitchfork' is 1.6, while the newest version is 1.8.
Can it be the problem?

Will appreciate your help on the issue.

Thank you,
Roman

**Comment by pb-dseifert** [comment]
Sorry, we do not support source builds anymore. You can try the new (and only remaining) build system Meson, but we will not help with troubleshooting. You can get pre-built binaries for Linux and macOS using bioconda easily via `conda install -c bioconda bax2bam`.

**Comment by Patr26ck** [comment]
Dear David:

is it possible to use bioconda to install blasr and unanimity at present ?

Thanks !!

**Comment by pb-dseifert** [comment]
@Patr26ck you can install `blasr` from bioconda just fine. `unanimity` cannot be used from bioconda yet, but GC+CCS will be on bioconda soon!

**Comment by Patr26ck** [comment]
Thanks a lot! I'll have a try.
