### ISSUE TITLE
converting technote-ecoli-native-raw-reads-1.3.1 RSII data to BAM fails

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/bax2bam#3]
Does not work with E.Coli methylation data from   https://github.com/PacificBiosciences/DevNet/wiki/E%20coli%20K12%20MG1655%20Methylome 
 (technote-ecoli-native-raw-reads-1.3.1) which seems to be too old for conversion.
Any idea how I could convert this training methylation data to BAM for import in SMRTLInk 5.1?
Thanks

```
bax2bam $(find . -name "*.bas.h5")
ERROR: unsupported sequencing chemistry combination: 
    binding kit:        001672551
    sequencing kit:     001558034
    basecaller version: 1.3.0.50.104209

ERROR: BindingKit, SequencingKit, and ChangeListID are mandatory but unavailable
```

**Comment by pb-dseifert** [comment]
This is a C2 dataset from 2011, which is unsupported at this point.

**Comment by splaisan** [comment]
Sad to hear that this one is also not usable.
Is there any bacterial dataset that one can use today to practice Motif/methylation analysis?
A number of PB pages used to relate to this topic and some recently disappeared and I am left with links and claims in your home page that this type of analysis can be done but no data to try/learn it properly.
Thanks inadvance

**Comment by armintoepfer** [comment]
Please contact your local PacBio representative for further information. This repository is about `bax2bam` and we can't provide further help.

**Comment by jrharting** [comment]
you could use the multiplexed bacterial data here:
https://github.com/PacificBiosciences/DevNet/wiki/microbial-multiplexing-data-set

methylation analysis is available 'by default' for most whole genome data, including this example dataset.  Because this is a test dataset, some of the barcoded samples are replicates, so if you need more coverage you can combine subsets.

**Comment by splaisan** [comment]
Thanks you John, this helped a lot and I discovered the other datasets placed there which will also be helpful for other applications.
Best
Stephane

**Comment by splaisan** [comment]
HI again John, I use this channel as I do not have your direct mail
I loaded the 10plex data into SMRTLink 5.1 but do not get the data split by genome and therefore cannot isolate the 4 EColi to merge them.
There seem to be files lacking in the targz in order to reconstitute the subsample split and all gets loaded as one single genome data.
Any idea how to recover the data as shown in https://www.pacb.com/wp-content/uploads/Analysis-Procedure-Multiplexed-Microbial-Assembly-with-SMRT-Link-v510.pdf which I would also like to reproduce for self training?
Thanks

**Comment by jrharting** [comment]
Hi Stephane,

I am pretty sure the subreads bam should have barcode bin and (bcf/bcr) and barcode quality (bq) tags for each row. The bcf/bcr values correspond to the 0-based index of the barcode labels from the barcode fasta.

The `dataset` tool can be used to generate per-barcode views of each barcode

`dataset split --barcodes [args]`

You can also generate multi-barcode views with `dataset filter`

`dataset filter in.subreadset.xml bc0_bc1.subreadset.xml 'bcf=0' 'bcf=1'`

Finally, you can generate new copies of each dataset.xml view using the tool `pbmerge` if you desire.

You can email me directly for additional questions.  Use jharting at pacificbiosciences dot com.

Cheers,
John

**Comment by jrharting** [comment]
my bad, the instructions pdf suggest that there are no barcodes in the raw data.  If you do not have access to a SMRT-Link v5.1 server, then you will need to call the barcodes using the barcodeset listed in the pdf and the CL program `lima`.  Make sure to use the `--split-bam-named` option and it will split the bams for you without going though the steps outline above.

Please email at address above for addition help if needed!
