### ISSUE TITLE
cannot use conda version

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/bax2bam#4]
bax2bam was installed with: conda install -c bioconda bax2bam

Then when running I have:
bax2bam ./sc/orga/projects/pacbio/userdata_permanent/raw/HG003new_H1_HG004new_H1_P6_C4_MB_577/A01_1/Analysis_Results/m150206_030048_42156_c100779872550000001823165208251550_s1_p0.1.bax.h5 
bax2bam: symbol lookup error: /auto/cmb-16/mjc/shared/miniconda/bin/../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

**Comment by joelmartin** [comment]
Hi, @pb-dseifert.   I just got this from an install started and completed this morning.   I ran conda install -c bioconda blasr before the conda install -c bioconda bax2bam if it matters.   

mostly had followed steps from https://iamphioxus.org/2017/05/04/custom-installation-of-pacbios-genomicconsensus-quiver and ended with the packages below when getting this error.

bax2bam=0.0.9=hac9d22c_3
blas=1.0=mkl
blasr=5.3.2=hac9d22c_3
blasr_libcpp=5.3.1=hac9d22c_2
bzip2=1.0.6=h14c3975_5
ca-certificates=2018.03.07=0
certifi=2018.4.16=py27_0
curl=7.61.0=h84994c4_0
h5py=2.8.0=py27h8d01980_0
hdf5=1.10.2=hba1933b_1
htslib=1.7=0
intel-openmp=2018.0.3=0
libcurl=7.61.0=h1ad7b7a_0
libedit=3.1.20170329=h6b74fdf_2
libffi=3.2.1=hd88cf55_4
libgcc=7.2.0=h69d50b8_2
libgcc-ng=7.2.0=hdf63c60_3
libgfortran-ng=7.2.0=hdf63c60_3
libssh2=1.8.0=h9cfc8f7_4
libstdcxx-ng=7.2.0=hdf63c60_3
linecache2=1.0.0=py27_0
mkl=2018.0.3=1
mkl_fft=1.0.2=py27h651fb7a_0
mkl_random=1.0.1=py27h4414c95_1
ncurses=6.1=hf484d3e_0
numpy=1.14.5=py27h1b885b7_4
numpy-base=1.14.5=py27hdbf6ddf_4
openssl=1.0.2o=h20670df_0
pbbam=0.18.0=h1310cd9_1
pip=10.0.1=py27_0
python=2.7.15=h1571d57_0
readline=7.0=ha6073c6_4
setuptools=39.2.0=py27_0
six=1.11.0=py27_1
sqlite=3.24.0=h84994c4_0
tk=8.6.7=hc745277_3
traceback2=1.4.0=py27_0
unittest2=1.1.0=py27_0
wheel=0.31.1=py27_0
xz=5.2.4=h14c3975_4
zlib=1.2.11=ha838bed_2

**Comment by pb-dseifert** [comment]
I cannot reproduce this problem for the life of me.

1. Can you please try running `conda update --all`?
2. What output do you get for

```
$ nm -D /path/to/conda/prefix/lib/./libhdf5_cpp.so.102.0.0 | grep _ZNK2H510H5Location15getObjnameByIdxEy
0000000000037490 T _ZNK2H510H5Location15getObjnameByIdxEy
00000000000377c0 T _ZNK2H510H5Location15getObjnameByIdxEyPcm
0000000000037930 T _ZNK2H510H5Location15getObjnameByIdxEyRSsm
```

**Comment by mchaisso** [comment]
Just in case I unset LD_LIBRARY_PATH.
Here is the nm result:

nm -D /auto/cmb-16/mjc/shared/miniconda/bin/../lib/libblasr.so.5.3.1 | grep
_ZNK2H510H5Location15getObjnameByIdxEy                  U
_ZNK2H510H5Location15getObjnameByIdxEy

**Comment by joelmartin** [comment]
for me the conda update --all updated numpy base and numpy to 1.15.0 and mkl_fft

the undefined symbol looks like it should be coming from hdf5 libhdf5_cpp.so.101.0.0, but i have that linked.

nm -D /global/projectb/scratch/myself/pacbio-install/lib/./libhdf5_cpp.so.102.0.0 | grep _ZNK2H510H5Location15getObjnameByIdxEy
000000000003a210 T _ZNK2H510H5Location15getObjnameByIdxEyPcm
000000000003a3a0 T _ZNK2H510H5Location15getObjnameByIdxEyRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEm

also, this is what's linked.

ldd `which bax2bam`
	linux-vdso.so.1 (0x00007fff94607000)
	libhdf5_cpp.so.102 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/libhdf5_cpp.so.102 (0x00002b4be5842000)
	libblasr.so.5.3.1 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/libblasr.so.5.3.1 (0x00002b4be5ab2000)
	libpbbam.so.0.18.0 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/libpbbam.so.0.18.0 (0x00002b4be5fe6000)
	libstdc++.so.6 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/libstdc++.so.6 (0x00002b4be63f6000)
	libgcc_s.so.1 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/libgcc_s.so.1 (0x00002b4be6730000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b4be695c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b4be6d00000)
	libhdf5.so.101 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/./libhdf5.so.101 (0x00002b4be6f1d000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b4be74b0000)
	libz.so.1 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/./libz.so.1 (0x00002b4be76b9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b4be78d0000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b4be7ad4000)
	libhts.so.2 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/./libhts.so.2 (0x00002b4be7dd2000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b4be561f000)
	liblzma.so.5 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/././liblzma.so.5 (0x00002b4be809f000)
	libbz2.so.1.0 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/././libbz2.so.1.0 (0x00002b4be82c6000)
	libcurl.so.4 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/././libcurl.so.4 (0x00002b4be84d8000)
	libcrypto.so.1.0.0 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/././libcrypto.so.1.0.0 (0x00002b4be874d000)
	libssl.so.1.0.0 => /global/projectb/scratch/myself/pacbio-install/bin/../lib/./././libssl.so.1.0.0 (0x00002b4be8b8e000)

**Comment by pb-dseifert** [comment]
@mchaisso on `libhdf5_cpp.so.102` not `libblasr.so.5.3.1`. It's obvious that it wont be defined in `libblasr.so.5.3.1`.

**Comment by pb-dseifert** [comment]
Have you people set the right channel priorities? https://bioconda.github.io:

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

Previously, [it used to be](https://web.archive.org/web/20170508140632/https://bioconda.github.io)

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda

```
That is, without setting up channel priorities correctly, your conda will download hdf5 from `defaults` and not `conda-forge`. blasr_libcpp is built against the hdf5 from conda-forge, not defaults.

**Comment by pb-dseifert** [comment]
I could finally reproduce this issue. All of these problems stem from incorrectly set up channel priorities. If `defaults` is higher than `conda-forge`, you are living in a state of sin and will eventually run into issues. Signs of a **bad** setup:

```
The following NEW packages will be INSTALLED:

    bax2bam:        0.0.9-hac9d22c_3  bioconda
    blasr_libcpp:   5.3.1-hac9d22c_2  bioconda
    bzip2:          1.0.6-h14c3975_5
    curl:           7.61.0-h84994c4_0
    hdf5:           1.10.2-hba1933b_1
    htslib:         1.7-0             bioconda
    libcurl:        7.61.0-h1ad7b7a_0
    libgcc:         7.2.0-h69d50b8_2
    libgfortran-ng: 7.2.0-hdf63c60_3
    libssh2:        1.8.0-h9cfc8f7_4
    pbbam:          0.18.0-h1310cd9_1 bioconda

```

With a **good** setup, you should see:

```
The following NEW packages will be INSTALLED:

    bax2bam:         0.0.9-hac9d22c_3  bioconda
    blasr_libcpp:    5.3.1-hac9d22c_2  bioconda
    bzip2:           1.0.6-h470a237_2  conda-forge
    curl:            7.61.0-h93b3f91_1 conda-forge
    hdf5:            1.10.2-hc401514_1 conda-forge
    htslib:          1.7-0             bioconda
    krb5:            1.14.6-0          conda-forge
    libgcc:          7.2.0-h69d50b8_2
    libgfortran:     3.0.0-1
    libssh2:         1.8.0-h5b517e9_2  conda-forge
    pbbam:           0.18.0-h1310cd9_1 bioconda
```

Notice the additional `conda-forge` channel in the third column.

**Comment by mchaisso** [comment]
Haha, I should have noticed that...  I used your updates to the conda
channels, and bax2bam is working like a charm.  Thanks!

-Mark
